#!/bin/bash

KEGG_ID=$1
MET3D_ID=$2
DATASHEET_FILE="../molecules/3dmet_"$MET3D_ID".htm"

./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Formal charge" "3DMET_FORMAL_CHARGE"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Weight" "3DMET_WEIGHT"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "LogP(o/w)" "3DMET_LOGP_O_TO_W"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "SlogP" "3DMET_SLOGP"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "SMR" "3DMET_SMR"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "TPSA" "3DMET_TPSA"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Number of rings" "3DMET_NUMBER_OF_RINGS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Number of atoms" "3DMET_NUMBER_OF_ATOMS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Chiral atoms" "3DMET_CHIRAL_ATOMS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "H-bond acceptor" "3DMET_HBOND_ACCEPTOR"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "H-bond donor" "3DMET_HBOND_DONOR"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Acidic atoms" "3DMET_ACIDIC_ATOMS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Basic atoms" "3DMET_BASIC_ATOMS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Aromatic atoms" "3DMET_AROMATIC_ATOMS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Heavy atoms" "3DMET_HEAVY_ATOMS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Number of bonds" "3DMET_NUMBER_OF_BONDS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Single bonds" "3DMET_SINGLE_BONDS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Rotatable single bonds" "3DMET_ROTATABLE_SINGLE_BONDS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Double bonds" "3DMET_DOUBLE_BONDS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Triple bonds" "3DMET_TRIPLE_BONDS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Aromatic bonds" "3DMET_AROMATIC_BONDS"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Volume" "3DMET_VOLUME"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "ASA" "3DMET_ASA"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "VSA" "3DMET_VSA"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Density" "3DMET_DENSITY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Diameter" "3DMET_DIAMETER"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Dipole" "3DMET_DIPOLE"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Globularity" "3DMET_GLOBULARITY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Potential energy" "3DMET_POTENTIAL_ENERGY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "angle bend energy" "3DMET_ANGLE_BEND_ENERGY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "electrostatic energy" "3DMET_ELECTROSTATIC_ENERGY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "non-bond energy" "3DMET_NONBOND_ENERGY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "out-of-plane energy" "3DMET_OUTOFPLANE_ENERGY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "solvation energy" "3DMET_SOLVATION_ENERGY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "bond stretch-bend energy" "3DMET_BOND_STRETCHBEND_ENERGY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "torsion energy" "3DMET_TORSION_ENERGY"
./store_molecule_property_if_extant.sh $KEGG_ID $DATASHEET_FILE "Van del Waals energy" "3DMET_VAN_DEL_WAALS_ENERGY"
